export const vehiclesData = [
	{
		title: "Maruti 2008 Model",
		rentPerDay: "$350",
		images: {
			fullView: [
				{ src: "/assets/images/post/list-image-two.jpg", alt: "post" },
				{ src: "/assets/images/post/list-image-two.jpg", alt: "post" },
				{ src: "/assets/images/post/list-image-three.jpg", alt: "post" },
				{ src: "/assets/images/post/list-image-four.jpg", alt: "post" },
				{ src: "/assets/images/post/list-image-five.jpg", alt: "post" },
				{ src: "/assets/images/post/list-image-six.jpg", alt: "post" },
			],
			listView: [
				{ src: "/assets/images/post/list-image-one.jpg", alt: "post-image" },
				{ src: "/assets/images/post/list-image-two.jpg", alt: "post-image" },
				{ src: "/assets/images/post/list-image-three.jpg", alt: "post-image" },
				{ src: "/assets/images/post/list-image-four.jpg", alt: "post-image" },
				{ src: "/assets/images/post/list-image-five.jpg", alt: "post-image" },
				{ src: "/assets/images/post/list-image-six.jpg", alt: "post-image" },
			],
		},
		priceDetails: [
			{ label: "Rent/Day", value: "$150 (negotiable)" },
			{ label: "Rent/Week", value: "$900 (negotiable)" },
			{ label: "Rent/Month", value: "$3000 (negotiable)" },
			{
				label: "Service Charge",
				value: "150 USD per month, subject to change",
			},
			{ label: "Security Deposit", value: "All Security's Company" },
			{ label: "Servicing", value: "Servicing free" },
		],
		overview: [
			{ label: "Class", value: "Compact" },
			{ label: "Price from", value: "8.26 USD / day" },
			{ label: "Gear box", value: "Auto" },
			{ label: "Mileage", value: "Unlimited" },
			{ label: "Max passengers", value: "5" },
			{ label: "Fuel", value: "Octen/Petrol" },
			{ label: "Max luggage", value: "1" },
			{ label: "Fuel usage", value: "5-6/100km" },
			{ label: "Doors", value: "4" },
			{ label: "Engine capacity", value: "1400 ccm" },
			{ label: "Deposit", value: "110.00 USD" },
		],
		features: {
			internal: [
				"A/C full-time",
				"Audio Music",
				"Video Music",
				"Special Set",
				"Fire exit",
				"Sound Proof",
				"Satellite Tracker",
				"Car Heater",
				"Mineral Water",
				"Cold Drinks",
			],
			external: [
				"4 Doors",
				"2 Outlooking Glass",
				"Awesome Balance System",
				"Powerful Head Light",
				"Backup Fuel",
				"Emergency Break",
				"Emergency Safety Tools",
			],
		},
	},
];
