// lib/countries.ts
// Países com o código numérico ISO 3166-1 (3 dígitos) exigido pelo
// pagamento vinti4 / 3DSServer 2.2.0 no campo billAddrCountry (ex: Cabo
// Verde = "132"). Gerado a partir do pacote iso-codes (nomes em português).

export type Country = { code: string; alpha2: string; name: string };

export const DEFAULT_COUNTRY_CODE = "132";

export const COUNTRIES: Country[] = [
	{ code: "004", alpha2: "AF", name: "Afeganistão" },
	{ code: "710", alpha2: "ZA", name: "África do Sul" },
	{ code: "008", alpha2: "AL", name: "Albânia" },
	{ code: "276", alpha2: "DE", name: "Alemanha" },
	{ code: "020", alpha2: "AD", name: "Andorra" },
	{ code: "024", alpha2: "AO", name: "Angola" },
	{ code: "660", alpha2: "AI", name: "Anguilla" },
	{ code: "010", alpha2: "AQ", name: "Antártida" },
	{ code: "028", alpha2: "AG", name: "Antígua e Barbuda" },
	{ code: "682", alpha2: "SA", name: "Arábia Saudita" },
	{ code: "012", alpha2: "DZ", name: "Argélia" },
	{ code: "032", alpha2: "AR", name: "Argentina" },
	{ code: "051", alpha2: "AM", name: "Arménia" },
	{ code: "533", alpha2: "AW", name: "Aruba" },
	{ code: "036", alpha2: "AU", name: "Austrália" },
	{ code: "040", alpha2: "AT", name: "Áustria" },
	{ code: "031", alpha2: "AZ", name: "Azerbaijão" },
	{ code: "044", alpha2: "BS", name: "Bahamas" },
	{ code: "050", alpha2: "BD", name: "Bangladeche" },
	{ code: "052", alpha2: "BB", name: "Barbados" },
	{ code: "048", alpha2: "BH", name: "Barém" },
	{ code: "056", alpha2: "BE", name: "Bélgica" },
	{ code: "084", alpha2: "BZ", name: "Belize" },
	{ code: "204", alpha2: "BJ", name: "Benim" },
	{ code: "060", alpha2: "BM", name: "Bermudas" },
	{ code: "112", alpha2: "BY", name: "Bielorússia" },
	{ code: "104", alpha2: "MM", name: "Birmânia" },
	{ code: "068", alpha2: "BO", name: "Bolívia, Estado Plurinacional da" },
	{ code: "535", alpha2: "BQ", name: "Bonaire, Santo Eustáquio e Saba" },
	{ code: "070", alpha2: "BA", name: "Bósnia e Herzegovina" },
	{ code: "072", alpha2: "BW", name: "Botsuana" },
	{ code: "076", alpha2: "BR", name: "Brasil" },
	{ code: "096", alpha2: "BN", name: "Brunei" },
	{ code: "100", alpha2: "BG", name: "Bulgária" },
	{ code: "854", alpha2: "BF", name: "Burkina Faso" },
	{ code: "108", alpha2: "BI", name: "Burundi" },
	{ code: "064", alpha2: "BT", name: "Butão" },
	{ code: "132", alpha2: "CV", name: "Cabo Verde" },
	{ code: "120", alpha2: "CM", name: "Camarões" },
	{ code: "116", alpha2: "KH", name: "Camboja" },
	{ code: "124", alpha2: "CA", name: "Canadá" },
	{ code: "634", alpha2: "QA", name: "Catar" },
	{ code: "398", alpha2: "KZ", name: "Cazaquistão" },
	{ code: "148", alpha2: "TD", name: "Chade" },
	{ code: "203", alpha2: "CZ", name: "Chéquia" },
	{ code: "152", alpha2: "CL", name: "Chile" },
	{ code: "156", alpha2: "CN", name: "China" },
	{ code: "196", alpha2: "CY", name: "Chipre" },
	{ code: "170", alpha2: "CO", name: "Colômbia" },
	{ code: "174", alpha2: "KM", name: "Comores" },
	{ code: "178", alpha2: "CG", name: "Congo" },
	{ code: "180", alpha2: "CD", name: "Congo, República Democrática do" },
	{ code: "410", alpha2: "KR", name: "Coreia, República da" },
	{ code: "408", alpha2: "KP", name: "Coreia, República Popular Democrática da" },
	{ code: "384", alpha2: "CI", name: "Costa do Marfim" },
	{ code: "188", alpha2: "CR", name: "Costa Rica" },
	{ code: "191", alpha2: "HR", name: "Croácia" },
	{ code: "192", alpha2: "CU", name: "Cuba" },
	{ code: "531", alpha2: "CW", name: "Curação" },
	{ code: "208", alpha2: "DK", name: "Dinamarca" },
	{ code: "262", alpha2: "DJ", name: "Djibouti" },
	{ code: "212", alpha2: "DM", name: "Dominica" },
	{ code: "818", alpha2: "EG", name: "Egito" },
	{ code: "222", alpha2: "SV", name: "El Salvador" },
	{ code: "784", alpha2: "AE", name: "Emirados Árabes Unidos" },
	{ code: "218", alpha2: "EC", name: "Equador" },
	{ code: "232", alpha2: "ER", name: "Eritreia" },
	{ code: "703", alpha2: "SK", name: "Eslováquia" },
	{ code: "705", alpha2: "SI", name: "Eslovénia" },
	{ code: "724", alpha2: "ES", name: "Espanha" },
	{ code: "840", alpha2: "US", name: "Estados Unidos" },
	{ code: "233", alpha2: "EE", name: "Estónia" },
	{ code: "231", alpha2: "ET", name: "Etiópia" },
	{ code: "643", alpha2: "RU", name: "Federação Russa" },
	{ code: "242", alpha2: "FJ", name: "Fiji" },
	{ code: "608", alpha2: "PH", name: "Filipinas" },
	{ code: "246", alpha2: "FI", name: "Finlândia" },
	{ code: "250", alpha2: "FR", name: "França" },
	{ code: "266", alpha2: "GA", name: "Gabão" },
	{ code: "288", alpha2: "GH", name: "Gana" },
	{ code: "268", alpha2: "GE", name: "Geórgia" },
	{ code: "292", alpha2: "GI", name: "Gibraltar" },
	{ code: "308", alpha2: "GD", name: "Granada" },
	{ code: "300", alpha2: "GR", name: "Grécia" },
	{ code: "304", alpha2: "GL", name: "Gronelândia" },
	{ code: "312", alpha2: "GP", name: "Guadalupe" },
	{ code: "316", alpha2: "GU", name: "Guam" },
	{ code: "320", alpha2: "GT", name: "Guatemala" },
	{ code: "831", alpha2: "GG", name: "Guernsey" },
	{ code: "328", alpha2: "GY", name: "Guiana" },
	{ code: "254", alpha2: "GF", name: "Guiana Francesa" },
	{ code: "324", alpha2: "GN", name: "Guiné" },
	{ code: "226", alpha2: "GQ", name: "Guiné Equatorial" },
	{ code: "624", alpha2: "GW", name: "Guiné-Bissáu" },
	{ code: "270", alpha2: "GM", name: "Gâmbia" },
	{ code: "332", alpha2: "HT", name: "Haiti" },
	{ code: "340", alpha2: "HN", name: "Honduras" },
	{ code: "344", alpha2: "HK", name: "Hong Kong" },
	{ code: "348", alpha2: "HU", name: "Hungria" },
	{ code: "887", alpha2: "YE", name: "Iémen" },
	{ code: "074", alpha2: "BV", name: "Ilha Bouvet" },
	{ code: "833", alpha2: "IM", name: "Ilha de Man" },
	{ code: "334", alpha2: "HM", name: "Ilha Heard e Ilhas McDonald" },
	{ code: "162", alpha2: "CX", name: "Ilha Natal" },
	{ code: "574", alpha2: "NF", name: "Ilha Norfolk" },
	{ code: "638", alpha2: "RE", name: "Ilha Reunião" },
	{ code: "248", alpha2: "AX", name: "Ilhas Alanda" },
	{ code: "136", alpha2: "KY", name: "Ilhas Caimão" },
	{ code: "166", alpha2: "CC", name: "Ilhas Cocos" },
	{ code: "184", alpha2: "CK", name: "Ilhas Cook" },
	{ code: "238", alpha2: "FK", name: "Ilhas Falkland (Malvinas)" },
	{ code: "234", alpha2: "FO", name: "Ilhas Faroé" },
	{ code: "239", alpha2: "GS", name: "Ilhas Geórgia do Sul e Sandwich do Sul" },
	{ code: "580", alpha2: "MP", name: "Ilhas Marianas do Norte" },
	{ code: "584", alpha2: "MH", name: "Ilhas Marshall" },
	{ code: "581", alpha2: "UM", name: "Ilhas Menores Distantes dos Estados Unidos" },
	{ code: "090", alpha2: "SB", name: "Ilhas Salomão" },
	{ code: "796", alpha2: "TC", name: "Ilhas Turcas e Caicos" },
	{ code: "092", alpha2: "VG", name: "Ilhas Virgens, Britânicas" },
	{ code: "850", alpha2: "VI", name: "Ilhas Virgens, Estados Unidos" },
	{ code: "356", alpha2: "IN", name: "Índia" },
	{ code: "360", alpha2: "ID", name: "Indonésia" },
	{ code: "368", alpha2: "IQ", name: "Iraque" },
	{ code: "372", alpha2: "IE", name: "Irlanda" },
	{ code: "364", alpha2: "IR", name: "Irão, República Islâmica do" },
	{ code: "352", alpha2: "IS", name: "Islândia" },
	{ code: "376", alpha2: "IL", name: "Israel" },
	{ code: "380", alpha2: "IT", name: "Itália" },
	{ code: "388", alpha2: "JM", name: "Jamaica" },
	{ code: "392", alpha2: "JP", name: "Japão" },
	{ code: "832", alpha2: "JE", name: "Jersey" },
	{ code: "400", alpha2: "JO", name: "Jordânia" },
	{ code: "296", alpha2: "KI", name: "Kiribati" },
	{ code: "414", alpha2: "KW", name: "Kuwait" },
	{ code: "426", alpha2: "LS", name: "Lesoto" },
	{ code: "428", alpha2: "LV", name: "Letónia" },
	{ code: "422", alpha2: "LB", name: "Líbano" },
	{ code: "430", alpha2: "LR", name: "Libéria" },
	{ code: "434", alpha2: "LY", name: "Líbia" },
	{ code: "438", alpha2: "LI", name: "Liechtenstein" },
	{ code: "440", alpha2: "LT", name: "Lituânia" },
	{ code: "442", alpha2: "LU", name: "Luxemburgo" },
	{ code: "446", alpha2: "MO", name: "Macau" },
	{ code: "807", alpha2: "MK", name: "Macedónia do Norte" },
	{ code: "450", alpha2: "MG", name: "Madagáscar" },
	{ code: "458", alpha2: "MY", name: "Malásia" },
	{ code: "454", alpha2: "MW", name: "Malawi" },
	{ code: "462", alpha2: "MV", name: "Maldivas" },
	{ code: "466", alpha2: "ML", name: "Mali" },
	{ code: "470", alpha2: "MT", name: "Malta" },
	{ code: "504", alpha2: "MA", name: "Marrocos" },
	{ code: "474", alpha2: "MQ", name: "Martinica" },
	{ code: "480", alpha2: "MU", name: "Maurícia" },
	{ code: "478", alpha2: "MR", name: "Mauritânia" },
	{ code: "175", alpha2: "YT", name: "Mayotte" },
	{ code: "484", alpha2: "MX", name: "México" },
	{ code: "583", alpha2: "FM", name: "Micronésia, Estados Federados da" },
	{ code: "508", alpha2: "MZ", name: "Moçambique" },
	{ code: "498", alpha2: "MD", name: "Moldávia, República da" },
	{ code: "492", alpha2: "MC", name: "Mónaco" },
	{ code: "496", alpha2: "MN", name: "Mongólia" },
	{ code: "500", alpha2: "MS", name: "Monserrate" },
	{ code: "499", alpha2: "ME", name: "Montenegro" },
	{ code: "516", alpha2: "NA", name: "Namíbia" },
	{ code: "520", alpha2: "NR", name: "Nauru" },
	{ code: "524", alpha2: "NP", name: "Nepal" },
	{ code: "558", alpha2: "NI", name: "Nicarágua" },
	{ code: "562", alpha2: "NE", name: "Níger" },
	{ code: "566", alpha2: "NG", name: "Nigéria" },
	{ code: "570", alpha2: "NU", name: "Niue" },
	{ code: "578", alpha2: "NO", name: "Noruega" },
	{ code: "540", alpha2: "NC", name: "Nova Caledónia" },
	{ code: "554", alpha2: "NZ", name: "Nova Zelândia" },
	{ code: "512", alpha2: "OM", name: "Omã" },
	{ code: "528", alpha2: "NL", name: "Países Baixos" },
	{ code: "585", alpha2: "PW", name: "Palau" },
	{ code: "275", alpha2: "PS", name: "Palestina, Estado da" },
	{ code: "591", alpha2: "PA", name: "Panamá" },
	{ code: "598", alpha2: "PG", name: "Papua Nova Guiné" },
	{ code: "586", alpha2: "PK", name: "Paquistão" },
	{ code: "600", alpha2: "PY", name: "Paraguai" },
	{ code: "604", alpha2: "PE", name: "Peru" },
	{ code: "612", alpha2: "PN", name: "Pitcairn" },
	{ code: "258", alpha2: "PF", name: "Polinésia Francesa" },
	{ code: "616", alpha2: "PL", name: "Polónia" },
	{ code: "630", alpha2: "PR", name: "Porto Rico" },
	{ code: "620", alpha2: "PT", name: "Portugal" },
	{ code: "404", alpha2: "KE", name: "Quénia" },
	{ code: "417", alpha2: "KG", name: "Quirguistão" },
	{ code: "826", alpha2: "GB", name: "Reino Unido" },
	{ code: "760", alpha2: "SY", name: "República Árabe Síria" },
	{ code: "140", alpha2: "CF", name: "República Centro-Africana" },
	{ code: "418", alpha2: "LA", name: "República Democrática Popular do Laos" },
	{ code: "214", alpha2: "DO", name: "República Dominicana" },
	{ code: "642", alpha2: "RO", name: "Roménia" },
	{ code: "646", alpha2: "RW", name: "Ruanda" },
	{ code: "732", alpha2: "EH", name: "Saara Ocidental" },
	{ code: "652", alpha2: "BL", name: "Saint Barthélemy" },
	{ code: "666", alpha2: "PM", name: "Saint Pierre e Miquelon" },
	{ code: "882", alpha2: "WS", name: "Samoa" },
	{ code: "016", alpha2: "AS", name: "Samoa Americana" },
	{ code: "674", alpha2: "SM", name: "San Marino" },
	{ code: "654", alpha2: "SH", name: "Santa Helena, Ascensão e Tristão da Cunha" },
	{ code: "662", alpha2: "LC", name: "Santa Lúcia" },
	{ code: "336", alpha2: "VA", name: "Santa Sé (Estado da Cidade do Vaticano)" },
	{ code: "686", alpha2: "SN", name: "Senegal" },
	{ code: "694", alpha2: "SL", name: "Serra Leoa" },
	{ code: "688", alpha2: "RS", name: "Sérvia" },
	{ code: "690", alpha2: "SC", name: "Seychelles" },
	{ code: "702", alpha2: "SG", name: "Singapura" },
	{ code: "706", alpha2: "SO", name: "Somália" },
	{ code: "144", alpha2: "LK", name: "Sri Lanka" },
	{ code: "748", alpha2: "SZ", name: "Suazilândia" },
	{ code: "729", alpha2: "SD", name: "Sudão" },
	{ code: "728", alpha2: "SS", name: "Sudão do Sul" },
	{ code: "752", alpha2: "SE", name: "Suécia" },
	{ code: "756", alpha2: "CH", name: "Suíça" },
	{ code: "740", alpha2: "SR", name: "Suriname" },
	{ code: "744", alpha2: "SJ", name: "Svalbard e Jan Mayen" },
	{ code: "659", alpha2: "KN", name: "São Cristóvão e Nevis" },
	{ code: "663", alpha2: "MF", name: "São Martin (Território Francês)" },
	{ code: "534", alpha2: "SX", name: "São Martinho (Países Baixos)" },
	{ code: "678", alpha2: "ST", name: "São Tomé e Príncipe" },
	{ code: "670", alpha2: "VC", name: "São Vicente e Granadinas" },
	{ code: "764", alpha2: "TH", name: "Tailândia" },
	{ code: "158", alpha2: "TW", name: "Taiwan, Província da China" },
	{ code: "762", alpha2: "TJ", name: "Tajiquistão" },
	{ code: "834", alpha2: "TZ", name: "Tanzânia, República Unida da" },
	{ code: "086", alpha2: "IO", name: "Território Britânico do Oceano Índico" },
	{ code: "260", alpha2: "TF", name: "Territórios Franceses do Sul" },
	{ code: "626", alpha2: "TL", name: "Timor-Leste" },
	{ code: "768", alpha2: "TG", name: "Togo" },
	{ code: "772", alpha2: "TK", name: "Tokelau" },
	{ code: "776", alpha2: "TO", name: "Tonga" },
	{ code: "780", alpha2: "TT", name: "Trindade e Tobago" },
	{ code: "788", alpha2: "TN", name: "Tunísia" },
	{ code: "795", alpha2: "TM", name: "Turquemenistão" },
	{ code: "792", alpha2: "TR", name: "Turquia" },
	{ code: "798", alpha2: "TV", name: "Tuvalu" },
	{ code: "804", alpha2: "UA", name: "Ucrânia" },
	{ code: "800", alpha2: "UG", name: "Uganda" },
	{ code: "858", alpha2: "UY", name: "Uruguai" },
	{ code: "860", alpha2: "UZ", name: "Uzbequistão" },
	{ code: "548", alpha2: "VU", name: "Vanuatu" },
	{ code: "862", alpha2: "VE", name: "Venezuela, República Bolivariana da" },
	{ code: "704", alpha2: "VN", name: "Vietname" },
	{ code: "876", alpha2: "WF", name: "Wallis e Futuna" },
	{ code: "716", alpha2: "ZW", name: "Zimbábue" },
	{ code: "894", alpha2: "ZM", name: "Zâmbia" },
];

export function countryName(code: string | null | undefined): string {
	return COUNTRIES.find((c) => c.code === code)?.name ?? "";
}
